# Generated by Django 3.1.2 on 2020-10-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('speed', models.IntegerField(verbose_name='Speed of movement')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
